### PR TITLE
HarinaKhati/introduction.txt

### PR DESCRIPTION
**Pull request by harinakhati**

### CODE REVIEW

**Comment by sandeshkhadka** [comment]
Hey, your PR does not meet the requirements. Please go through the instruction and try again. You may have a look at other PR's that has been merged.

**Comment by harinakhati** [comment]
I want to delete them all and create the new one. But I couldn't delete
them. So could you please delete them all ??
Actually I don't have attended the session due to some network issues. So I
don't know how to pull request and to make the folder. I have tried to do
it on vs code but I couldn't.

**Comment by sandeshkhadka** [comment]
Okay, I am closing this PR, if you are lost then you can always delete the forked repository and create a new fork and start over. Good Luck.

**Comment by harinakhati** [comment]
Okay thank you.
Is there recorded video of the last session??

**Comment by harinakhati** [comment]
Could you please check my assignment now??

**Pull request closed without merging**
